### ISSUE TITLE
Build 1.0.8 does not contain an executable

### ISSUE THREAD

**Issue by MisinformedDNA** [Drise13/PetsOptimizer#6]
Build [1.0.8](https://github.com/Drise13/PetsOptimizer/releases/download/v1.0.8/PetsOptimizer.zip) does not contain an executable. Build 1.0.6 does and works fine.

**Comment by Drise13** [comment]
I think it has an executeable only for ubuntu. Trying an updated github action to build for windows.

**Comment by Drise13** [comment]
Fixed  in https://github.com/Drise13/PetsOptimizer/releases/tag/v1.0.10
